# Generated by Django 5.0.6 on 2024-06-05 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Toto pole musí být vyplněno'}, help_text='Napis název týmu', max_length=50, verbose_name='Název klubu')),
                ('misto', models.CharField(error_messages={'blank': 'Toto pole musí být vyplněno'}, help_text='Napis jméno města', max_length=30, verbose_name='Město')),
                ('zalozeni', models.IntegerField(blank=True, help_text='Napis rok založení', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Rok založení')),
                ('logo', models.ImageField(blank=True, help_text='Zadejte logo klubu', upload_to='loga', verbose_name='Logo klubu')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Kluby',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno cyklisty musí být vyplněno'}, help_text='Zadejte jméno hráče', max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení cyklisty musí být vyplněno'}, help_text='Zadejte příjmení hráče', max_length=50, verbose_name='Příjmení')),
                ('narozeni', models.DateField(blank=True, help_text='Zadejte datum narození', verbose_name='Datum narození')),
                ('fotka', models.ImageField(blank=True, upload_to='fotky', verbose_name='Nahrejte fotku hráče')),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapasy.klub', verbose_name='Klub')),
            ],
            options={
                'verbose_name': 'Hrac',
                'verbose_name_plural': 'Hraci',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(verbose_name='Datum zápasu')),
                ('domaci_skore', models.PositiveIntegerField(help_text='Vyber skóre domácího týmu', verbose_name='Skóre domácího týmu')),
                ('hostujici_skore', models.PositiveIntegerField(help_text='Vyber skóre hostujícího týmu', verbose_name='Skóre hostujícího týmu')),
                ('domaci_tym', models.ForeignKey(help_text='Vyber domácí tým', on_delete=django.db.models.deletion.CASCADE, related_name='domaci_tymy', to='zapasy.klub', verbose_name='domaci tým')),
                ('hostujici_tym', models.ForeignKey(help_text='Vyber tým hostů', on_delete=django.db.models.deletion.CASCADE, related_name='hostujici_tymy', to='zapasy.klub', verbose_name='hostující tým')),
            ],
            options={
                'verbose_name': 'Zápas',
                'verbose_name_plural': 'Zápasy',
                'ordering': ['-datum'],
            },
        ),
    ]
